name: Build and Release Walrus Site Builder

on:
  release:
    types: [created]

permissions:
  actions: read
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone Walrus Sites repository
        run: |
          git clone https://github.com/MystenLabs/walrus-sites.git

      - name: Download additional files
        run: |
          mkdir -p ./download
          curl -L https://storage.googleapis.com/mysten-walrus-binaries/site-builder-testnet-latest-ubuntu-x86_64 -o ./download/site-builder-x86_64
          curl -L https://storage.googleapis.com/mysten-walrus-binaries/walrus-testnet-latest-ubuntu-x86_64 -o ./download/walrus-x86_64

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./download/*
            ./walrus-sites/sites-config.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
